[build]
builder = "nixpacks"

[deploy]
startCommand = "node_modules/.bin/pm2-runtime ecosystem.config.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
region = "europe-west4"

[deploy.healthcheck]
path = "/health"
intervalSeconds = 30
timeoutSeconds  = 10
